/**
 * Seeds a handful of test users with real bcrypt-hashed passwords.
 * Run with: npm run seed:users
 *
 * This has to be a script rather than a .sql file because password
 * hashes must be generated by bcrypt at run time, not written as
 * plain SQL — a SQL INSERT can't compute a bcrypt hash itself.
 */
const bcrypt = require("bcryptjs");
const pool = require("../db/pool");

const USERS = [
  {
    name: "Vedant Pathak",
    email: "admin@mmcoe.edu",
    password: "Admin@123",
    roleName: "asset_admin",
    departmentName: "Computer Engineering",
    designation: "Team Lead",
  },
  {
    name: "Mahesh Kandekar",
    email: "depthead@mmcoe.edu",
    password: "DeptHead@123",
    roleName: "dept_head",
    departmentName: "Computer Engineering",
    designation: "Mentor / Department Head",
  },
  {
    name: "Arya Joshi",
    email: "staff@mmcoe.edu",
    password: "Staff@123",
    roleName: "staff",
    departmentName: "Computer Engineering",
    designation: "Staff",
  },
];

async function main() {
  for (const u of USERS) {
    const [roleRows] = await pool.query("SELECT role_id FROM roles WHERE role_name = ?", [
      u.roleName,
    ]);
    if (roleRows.length === 0) {
      console.error(`Role "${u.roleName}" not found — did you run seed.sql?`);
      continue;
    }
    const roleId = roleRows[0].role_id;

    const [deptRows] = await pool.query("SELECT department_id FROM departments WHERE name = ?", [
      u.departmentName,
    ]);
    const departmentId = deptRows.length > 0 ? deptRows[0].department_id : null;

    const passwordHash = await bcrypt.hash(u.password, 10);

    await pool.query(
      `INSERT INTO users (name, email, password_hash, role_id, department_id, designation, status)
       VALUES (?, ?, ?, ?, ?, ?, 'active')
       ON DUPLICATE KEY UPDATE password_hash = VALUES(password_hash), role_id = VALUES(role_id)`,
      [u.name, u.email, passwordHash, roleId, departmentId, u.designation]
    );

    console.log(`Seeded ${u.email} (${u.roleName}) — password: ${u.password}`);
  }

  await pool.end();
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
